tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'railwaycat/emacsmacport'
tap 'heroku/brew'

brew 'asdf'
brew 'aspell'
brew 'awscli'
brew 'bat'
brew 'cmake'
brew 'difftastic'
brew 'fzf'
brew 'gpg'
brew 'heroku'
brew 'neovim'
brew 'pandoc'
brew 'postgresql'
brew 'proselint'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'sqlite'
brew 'spaceship'
brew 'tig'
brew 'tmux'
brew 'tmuxinator'
brew 'trash'
brew 'tree'
brew 'vim'
brew 'yarn'
brew 'youtube-dl'
brew 'z'
brew 'zsh'
brew 'zsh-autosuggestions'

# Kicking the tires on these
brew 'exercism'
brew 'clojure/tools/clojure'

cask_args appdir: '/Applications'

# Quicklook for plain text files
cask 'qlstephen'

# Applications
#cask 'emacs'
cask 'airbuddy'
cask 'alfred'
cask 'aws-vault'
cask 'betterzip'
cask 'choosy'
cask 'cleanshot'
cask 'dash'
cask 'deckset'
cask 'discord'
cask 'docker'
cask 'emacs-mac'
cask 'expressvpn'
cask 'fantastical'
cask 'firefox'
cask 'flux'
cask 'grammarly'
cask 'imageoptim'
cask 'insomnia'
cask 'iterm2'
cask 'kaleidoscope'
cask 'karabiner-elements'
cask 'keybase'
cask 'kindle'
cask 'licecap'
cask 'mailplane'
cask 'marked'
cask 'monodraw'
cask 'moom'
cask 'omnigraffle'
cask 'postico'
cask 'sequel-pro'
# Failing as of 2021-09-10
# cask 'sizzy'
cask 'signal'
cask 'sketch'
cask 'soulver'
cask 'sourcetree'
cask 'spotify'
cask 'steam'
cask 'superduper'
cask 'tableplus'
cask 'toggl-track'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'
# These are already installed by JAMF
# cask 'google-chrome'
# cask 'zoom'
# cask 'slack'

