#!/usr/bin/env bash

# This script will (re)start the Emacs daemon process

EXISTING_PID=$(ps -x | grep "[E]macs --daemon" | cut -f 1 -d' ')

if [[ -n "$EXISTING_PID" ]]; then
  echo "Killing existing Emacs daemon"
  kill $EXISTING_PID
fi

/Applications/Emacs.app/Contents/MacOS/Emacs --daemon
