#!/bin/sh

# A script to convert movies to gifs
# From http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html#usage

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 input.mov output.gif"
  exit 1
fi

palette="/tmp/palette.png"

filters="fps=15,scale=320:-1:flags=lanczos"

ffmpeg -v warning -i $1 -vf "$filters,palettegen" -y $palette
ffmpeg -v warning -i $1 -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -y $2
