#!/usr/bin/env bash
##
## Usage: _PROG_ [session-name] [h/v]
##
## Create a new tmux session. Optionally split horizontally or vertically.
##

set -e

prog="$0"
me=`basename "$prog"`

dohelp () {
  grep '^##' "$prog" | sed -E -e 's/^## ?//' -e "s/_PROG_/$me/" 1>&2
}

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
  dohelp
  exit
fi

NAME=${1:-misc}

tmux new-session -d -n "$NAME" -s "$NAME"

case "$2" in
  h)
    tmux split-window -v -t "$NAME":"$NAME"
    ;;
  v)
    tmux split-window -h -t "$NAME":"$NAME"
    ;;
  *)
    ;;
esac


if [[ -z $TMUX ]]; then
  tmux attach-session -t "$NAME"
else
  tmux switch-client -t "$NAME"
fi
