#!/usr/bin/env bash
##
## Usage: _PROG_ [session-name]
##
## Create tmux sessions for identity dev.
##

set -e

prog="$0"
me=$(basename "$prog")

dohelp () {
  grep '^##' "$prog" | sed -E -e 's/^## ?//' -e "s/_PROG_/$me/" 1>&2
}

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
  dohelp
  exit
fi

NAME="${1:-misc}"

# Start the server if it's not already running so all the following commands register
if ! tmux info &> /dev/null; then
  tmux start-server
fi

if ! tmux has-session -t "$NAME" 2>/dev/null; then
  tmux new-session -d -c ~ -n "$NAME" -s "$NAME"

  case "$1" in
    dev)
      # Kick up my local dev tmux session
      tmux send-keys -t "$NAME":"$NAME" 'cd ~/.dotfiles' C-m
      tmux new-window -c ~/dev/dance.computer.dance -n "dance" -t "$NAME":2

      # I end up having to rename these for some reason
      tmux rename-window -t "$NAME":1 dotfiles
      tmux rename-window -t "$NAME":2 dance

      tmux select-window -t "$NAME":1
      ;;
    infra)
      tmux send-keys -t "$NAME":"$NAME" 'cd ~/src/customer-infrastructure' C-m
      ;;
    *)
      ;;
  esac
fi

if [[ -z $TMUX ]]; then
  tmux attach-session -t "$NAME"
else
  tmux switch-client -t "$NAME"
fi

