#!/usr/bin/env bash
##
## Usage: _PROG_ [session-name]
##
## Create tmux sessions for identity dev.
##

set -e

prog="$0"
me=$(basename "$prog")

dohelp () {
  grep '^##' "$prog" | sed -E -e 's/^## ?//' -e "s/_PROG_/$me/" 1>&2
}

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
  dohelp
  exit
fi

NAME="${1:-misc}"

# Start the server if it's not already running so all the following commands register
if ! tmux info &> /dev/null; then
  tmux start-server
fi

if ! tmux has-session -t "$NAME" 2>/dev/null; then
  tmux new-session -d -c ~ -n "$NAME" -s "$NAME"

  case "$1" in
    dev)
      # Kick up my local dev tmux session
      tmux send-keys -t "$NAME":"$NAME" 'cd ~/.dotfiles' C-m
      tmux rename-window dotfiles
      tmux new-window -c ~/dev -n dev -t "$NAME":2
      ;;
    admin)
      tmux send-keys -t "$NAME":"$NAME" 'cd ~/src/identity-admin' C-m
      ;;
    infra)
      tmux send-keys -t "$NAME":"$NAME" 'cd ~/src/identity-infrastructure' C-m
      ;;
    team)
      tmux send-keys -t "$NAME":"$NAME" 'cd ~/src/identity-team' C-m
      ;;
    sso)
      tmux send-keys -t "$NAME":"$NAME" 'cd ~/src/sso-server' C-m
      ;;
    ess)
      tmux send-keys -t "$NAME":"$NAME" 'cd ~/src/event_sourcery' C-m
      ;;
    identity)
      tmux send-keys -t "$NAME":"$NAME" 'cd ~/src/identity' C-m
      ;;
    analysis)
      tmux send-keys -t "$NAME":1.2 "cd ~/src/identity-infrastructure/aws-analysis" C-m
      ;;
    area51)
      tmux send-keys -t "$NAME":"$NAME" 'cd ~/src/area51-server' C-m
      ;;
    *)
      ;;
  esac
fi

if [[ -z $TMUX ]]; then
  tmux attach-session -t "$NAME"
else
  tmux switch-client -t "$NAME"
fi

