#!/usr/bin/env bash
##
## Usage: _PROG_ [session-name]
##
## Create tmux sessions for personal dev.
##

set -e

prog="$0"
me=`basename "$prog"`

dohelp () {
  grep '^##' "$prog" | sed -E -e 's/^## ?//' -e "s/_PROG_/$me/" 1>&2
}

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
  dohelp
  exit
fi

NAME="${1:-misc}"

tmux new-session -d -c ~ -n "$NAME" -s "$NAME"

case "$1" in
  dev)
    # Kick up my local dev tmux session
    tmux send-keys -t "$NAME":"$NAME" 'cd ~/.dotfiles' C-m
    tmux rename-window dotfiles
    tmux new-window -c ~/dev -n dev -t "$NAME":2
    ;;
  summate)
    tmux split-window -h -t $NAME:$NAME
    tmux split-window -v -t $NAME:$NAME
    tmux select-pane -t $NAME:1.1
    tmux send-keys -t $NAME:1.1 'cd ~/dev/summate' C-m
    tmux send-keys -t $NAME:1.2 "cd ~/dev/summate/backend; ./script/server" C-m
    tmux send-keys -t $NAME:1.3 "cd ~/dev/summate/ui; ./script/server" C-m
    ;;
  *)
    ;;
esac


if [[ -z $TMUX ]]; then
  tmux attach-session -t "$NAME"
else
  tmux switch-client -t "$NAME"
fi

