#!/usr/bin/env bash

rename_in_code() {
  from=$1
  to=$2
  git grep -l $from |xargs sed -i '' "s/$from/$to/g"
}

rename_files() {
  from=$1
  to=$2
  dirs=`find . ! -path '*/.git/*' ! -path '*/tmp/*' -type d -name "*$from*"`
  for orig in $dirs; do
    new=`echo $orig |sed "s/$from/$to/g"`
    cmd="mv $orig $new"
    echo $cmd
    $cmd
  done
  files=`find . ! -path '*/.git/*' ! -path '*/tmp/*' -type f -name "*$from*"`
  for orig in $files; do
    new=`echo $orig |sed "s/$from/$to/g"`
    cmd="mv $orig $new"
    echo $cmd
    $cmd
  done
}

rename_model() {
  dirs=( app config db features spec )
  dirs_list=`printf "%s " "${dirs[@]}"`

  if [ -z $2 ]; then
    echo "  Renames ActiveRecord model in code and filenames [ $dirs_list]"
    echo "  Usage: rename_model [from] [to]"
    echo "     eg: rename_model AdminUser Admin"
  else
    camelcased_from=`ruby -r 'active_support/core_ext/string' -e "puts '$1'.camelize"`
    camelcased_to=`ruby -r 'active_support/core_ext/string' -e "puts '$2'.camelize"`
    underscored_from=`ruby -r 'active_support/core_ext/string' -e "puts '$1'.underscore"`
    underscored_to=`ruby -r 'active_support/core_ext/string' -e "puts '$2'.underscore"`
    grep -lr $camelcased_from $dirs_list |xargs sed -i '' "s/$camelcased_from/$camelcased_to/g"
    grep -lr $underscored_from $dirs_list |xargs sed -i '' "s/$underscored_from/$underscored_to/g"
    for dir in "${dirs[@]}"
    do
      rename_files $underscored_from $underscored_to $dir/**/*
    done
  fi
}

rename_model
