#!/usr/bin/env bash

# Add all of my SSH keys to my agent

set -x

KEYS=(~/.ssh/id_rsa ~/.ssh/aws/identity-production-20180124-us-east-1.pem ~/.ssh/aws/identity-staging-2-ap-southeast-2.pem ~/.ssh/aws/identity-production-1-us-west-1.pem)

for KEY in "${KEYS[@]}"; do
  [[ -r $KEY ]] && ssh-add $KEY
done

