#!/usr/bin/env bash

# Add all of my SSH keys to my agent 

set -x

KEYS=(~/.ssh/id_rsa ~/.ssh/identity-production-1-us-east-1.pem ~/.ssh/identity-staging-2-ap-southeast-2.pem)

for KEY in "${KEYS[@]}"; do
  [[ -r $KEY ]] && ssh-add $KEY
done

