desc 'Link rc files'
task :link_rc_files do
  dest = File.expand_path("~/.vim")
  ln_s(Dir.pwd, dest) unless File.exist?(dest)

  dest = File.expand_path("~/.vimrc")
  ln_s(File.expand_path("../vimrc", __FILE__), dest) unless File.exist?(dest)
end

desc 'Install plugins via Vundle'
task :install do
  sh 'git clone https://github.com/gmarik/Vundle.vim.git bundle/Vundle.vim'
  puts 'Installing Vim plugins. This can take a while...'
  sh 'vim +PluginInstall +PluginClean +qall 2&> /dev/null' do
    # Ignore errors
  end
end

desc 'Create tmp directories'
task :create_temp_dirs do
  %w{undo backups}.each do |dir|
    sh "mkdir -p ~/.cache/vim/tmp/#{dir}"
  end
end

desc 'Setup a new installation'
task :setup => [:create_temp_dirs, :link_rc_files, :install]
