source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload
plug "andreyorst/fzf.kak" config %{
  map global user -docstring 'fzf' f ': fzf-mode<ret>'
  set-option global fzf_file_command 'rg'
}
plug "jjk96/kakoune-rainbow"
plug "h-youhei/kakoune-surround" config %{
  declare-user-mode surround
  map global surround s ':surround<ret>' -docstring 'surround'
  map global surround c ':change-surround<ret>' -docstring 'change'
  map global surround d ':delete-surround<ret>' -docstring 'delete'
  map global surround t ':select-surrounding-tag<ret>' -docstring 'select tag'
  map global user s ':enter-user-mode surround<ret>' -docstring 'Enter surround mode'
}
plug "alexherbo2/kakoune-dracula-theme" theme
colorscheme dracula

hook global WinCreate ^[^*]+$ %{
  add-highlighter window/ number-lines -hlcursor

  # Highlight for trailing whitespace
  add-highlighter window/ regex '\h+$' 0:Error
}

# No Clippy thanks
set global ui_options ncurses_assistant=none

# Show matching parens
add-highlighter global/ show-matching

# Clipboard
evaluate-commands %sh{
  case $(uname) in
    Linux) copy="xclip -i"; paste="xclip -o" ;;
    Darwin)  copy="pbcopy"; paste="pbpaste" ;;
  esac

  printf "map global user -docstring 'Paste (after) from clipboard' p '!%s<ret>'\n" "$paste"
  printf "map global user -docstring 'Paste (before) from clipboard' P '<a-!>%s<ret>'\n" "$paste"
  printf "map global user -docstring 'Yank to primary' y '<a-|>%s<ret>:echo -markup %%{{Information}copied selection to X11 primary}<ret>'\n" "$copy"
  printf "map global user -docstring 'Yank to clipboard' Y '<a-|>%s<ret>:echo -markup %%{{Information}copied selection to X11 clipboard}<ret>'\n" "$copy -selection clipboard"
  printf "map global user -docstring 'Replace from clipboard' R '|%s<ret>'\n" "$paste"
}

# Space as leader
map global normal <space> , -docstring 'leader'
# Assign comma to remove previous selection
map global normal , <space>

# User Mode (leader)
map global user -docstring 'Comment lines'                 c ': comment-line<ret>'
