
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'argon/homebrew-mas'
tap 'd12frosted/emacs-plus'

brew 'ansible'
brew 'aspell'
brew 'awscli'
brew 'chisel'
brew 'chruby'
brew 'ctags'
brew 'diff-so-fancy'

brew 'dnsmasq', restart_service: :changed

brew 'elixir'
brew 'figlet'
brew 'git'
brew 'gnupg2'
brew 'gnu-sed'
brew 'htop-osx'
brew 'heroku'
brew 'httpie'
brew 'imagemagick'
brew 'jq'
brew 'keybase'
brew 'leiningen'
brew 'macvim'
brew 'mercurial'
brew 'openssl'
brew 'pandoc'

brew 'postgresql', restart_service: :changed

brew 'pstree'
brew 'python'
brew 'reattach-to-user-namespace'
brew 'rust'
brew 'selecta'
brew 'sqlite'
brew 'the_silver_searcher'
brew 'tmate'
brew 'tmux'
brew 'trash'
brew 'tree'
brew 'vcprompt'
brew 'watchman'
brew 'wget'
brew 'youtube-dl'
brew 'z'
brew 'zsh'
brew 'vim', args: [ 'with-ruby', 'with-mzscheme', 'with-python' ]
brew 'd12frosted/emacs-plus/emacs-plus', args: ['with-cocoa', 'with-gnutls', 'with-imagemagick', 'with-librsvg', 'with-spacemacs-icon' ]
