tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'wallix/awless'
tap 'railwaycat/emacsmacport'

brew 'asdf'
brew 'aspell'
brew 'awless'
brew 'awscli'
brew 'chruby'
brew 'cmake'
brew 'ctags'
brew 'diff-so-fancy'
brew 'dnsmasq', restart_service: :changed
brew 'fzf'
brew 'git'
brew 'gnu-sed'
brew 'graphviz'
brew 'heroku'
brew 'httpie'
brew 'jq'
brew 'keybase'
brew 'libxml2'
brew 'pandoc'
brew 'postgresql', restart_service: :changed
brew 'pstree'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'rlwrap'
brew 'ruby-build'
brew 'sbcl'
brew 'sqlite'
brew 'tmux'
brew 'trash'
brew 'tree'
brew 'vim'
brew 'wget'
brew 'yarn'
brew 'proselint'
brew 'youtube-dl'
brew 'z'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'bat'

cask_args appdir: '/Applications'

cask 'aws-vault'
cask 'postico'
cask 'sequel-pro'

cask 'betterzip'
cask 'provisionql'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'webpquicklook'
cask 'karabiner-elements'

# Applications
#cask 'emacs'
cask 'emacs-mac'
cask 'alfred'
cask 'mailplane'
cask 'flux'
cask 'textexpander'
cask 'visual-studio-code'
# cask '1password'
cask 'docker'
cask 'slack'
cask 'vanilla'
cask 'spotify'
cask 'iterm2'
cask 'keybase'
cask 'moom'
cask 'monodraw'
cask 'marked'
cask 'kaleidoscope'
cask 'dash'
cask 'licecap'
cask 'kindle'
cask 'vlc'
cask 'omnigraffle'
cask 'deckset'
cask 'superduper'

tap 'argon/homebrew-mas'
mas 'Color Picker', id: 502401013
mas 'Day One', id: 1055511498
mas 'Monosnap', id: 540348655
mas 'Things 3', id: 904280696
mas 'Capo 3', id: 696977615
mas 'Clocks', id: 414554506
mas 'Affinity Photo', id: 824183456
mas 'MindNode 5', id: 1289197285
mas 'White Noise', id: 415139197
mas 'Soulver', id: 413965349
