tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'oven-sh/bun'
tap 'jesseduffield/lazygit'

brew 'asdf'
brew 'aspell'
brew 'awscli'
brew 'bat'
brew 'bkt'
brew 'bun'
brew 'cmake'
# Needed for building native ruby gems occasionally
brew 'coreutils'
brew 'difftastic'
brew 'ffmpeg'
brew 'flyctl'
brew 'fzf'
brew 'gum'
brew 'lazygit'
brew 'mas'
brew 'neovim'
brew 'pandoc'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'spaceship'
brew 'tmux'
brew 'tmuxinator'
brew 'trash'
brew 'tree'
brew 'yarn'
brew 'yt-dlp'
brew 'z'
brew 'zsh'
brew 'zsh-autosuggestions'

cask_args appdir: '/Applications'

# Quicklook for plain text files
cask 'qlstephen'

# Applications
cask '1password-cli'
cask 'alfred'
cask 'arc'
cask 'betterzip'
cask 'bike'
cask 'adobe-creative-cloud'
cask 'calibre'
cask 'cleanshot'
cask 'chatgpt'
cask 'claude'
cask 'dash'
cask 'expressvpn'
cask 'fantastical'
cask 'fork'
cask 'git-credential-manager'
cask 'ghostty'
cask 'google-chrome'
cask 'imageoptim'
cask 'intellij-idea-ce'
cask 'iterm2'
cask 'kaleidoscope'
cask 'karabiner-elements'
cask 'kindle'
cask 'mimestream'
cask 'marked'
cask 'monodraw'
cask 'moom'
cask 'omnigraffle'
cask 'orbstack'  # Docker
cask 'postico'
cask 'raycast'
cask 'retcon'
cask 'sabnzbd'
cask 'signal'
cask 'slack'
cask 'soulver'
cask 'spotify'
cask 'steam'
cask 'superduper'
cask 'tableplus'
cask 'textbuddy'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'
cask 'warp'
cask 'zoom'

