# Global Rubocop rules that play well with https://github.com/ruby-formatter/rufo
#
# Basically just keep lints and leave the style ones alone.

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'

Style:
  Enabled: false

Layout:
  Enabled: false

Metrics:
  Enabled: false

