# /Users/ray/.config/tmuxinator/project.yml

# A general two up project template project.
# Pass -n to tmuxinator to avoid name collisions.

name: project
root: ~/


windows:
  - editor:
      layout: even-horizontal
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - z <%= @args[0] %>
        - z <%= @args[0] %>
