if [ -f ~/.bashrc ]; then
. ~/.bashrc
fi



##
# Your previous /Users/ray/.bash_profile file was backed up as /Users/ray/.bash_profile.macports-saved_2009-09-07_at_22:03:58
##

# MacPorts Installer addition on 2009-09-07_at_22:03:58: adding an appropriate PATH variable for use with MacPorts.
#export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

